### PR TITLE
add support for jumbo messages with len > 255

### PR DESCRIPTION
**Pull request by catkira**
fixes https://github.com/christianrauch/msp/issues/59

### CODE REVIEW

**Comment by catkira** [comment]
let me know if you want some cleanup ;)

**Comment by christianrauch** [comment]
In https://github.com/christianrauch/msp/issues/59#issuecomment-1964674389 you mentioned that this is a bug in the flight controller (Betaflight) and the issue was closed. Does this PR still fix an issue?

**Comment by catkira** [comment]
yes, there was a bug in BF 4.3 that caused msp not to work despite this PR. With this fix it works with BF 4.5. Without this PR it is not working with BF 4.5.

**Comment by catkira** [comment]
author does not want to upstream it

**Pull request closed without merging**
